# -*- coding: utf-8 -*-
"""dm_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xwDv3X-1JSHwtuk51ae68hfY7N8GxdkA
"""

import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from matplotlib import pyplot as plt
from sklearn import tree

def pre_process_data(data):

    # Create Pandas Dataframe
    df = pd.DataFrame(data)

    # Drop irrelevant attributes from dataset (part of data cleaning)
    df.drop(['age', 'rbc', 'pcc', 'ba', 'cad', 'ane', 'su', 'bgr','sod','pot'], axis=1, inplace=True)

    # Make the dataset more readable
    df.replace('\t?', np.nan, inplace=True)
    df.replace('?', np.nan, inplace=True)

    # Assign values of 0 and 1 to binary attributes
    df['pc'].replace({'normal': 0, 'abnormal': 1}, inplace=True)
    df['htn'].replace({'no': 0, 'yes': 1}, inplace=True)
    df['dm'].replace({'no': 0, '\tno':0, '\tyes':1, ' yes':1, 'yes': 1}, inplace=True)
    df['pe'].replace({'no': 0, 'yes': 1}, inplace=True)
    df['appet'].replace({'poor': 0, 'good': 1}, inplace=True)

    extracted_features = ['bp', 'sg', 'al', 'pc', 'bu', 'sc', 'hemo', 'pcv', 'wbcc', 'rbcc', 'htn', 'dm', 'appet', 'pe']

    # Convert faetures to float values
    for feature in extracted_features:
        df[feature] = df[feature].astype(float)

    int_list = ['bp', 'al', 'pc', 'bu', 'pcv', 'wbcc', 'dm', 'appet', 'pe']
    float_list = ['sg', 'sc', 'hemo', 'rbcc', 'htn']

    # Fill missing values in dataset with the mean values
    for val in int_list:
        df[val].fillna(int(df[val].mean()), inplace=True)

    for val in float_list:
        df[val].fillna((df[val].mean()), inplace=True)

    df.to_csv('trimmed_data.csv')

    return df

# Train the classifier model
def train_classifier(df):

    # Make class values as 0 for notckd and 1 for ckd
    df.diagnosis = [1 if each == "ckd" else 0 for each in df.diagnosis]

    # y is the output class and x is the dataset exclding the class
    y = df.diagnosis.values
    x = df.drop(['diagnosis'], axis = 1)

    # Split the dataset for training an testing
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33)

    # Train the classifier
    dt = DecisionTreeClassifier(random_state = 0)
    dt.fit(x_train,y_train)
    print("score :",dt.score(x_test,y_test))

    return dt

# Plot the decision tree
def plot_decision_tree(dt):
    # This is the extracted features list
    features = ['blood pressure', 'specific gravity', 'albumin', 'pus cell', 'blood urea', 'serum creatinine', 'hemoglobin', 'packed cell volume', \
                'white blood cell count', 'red blood cell count', 'hypertension', 'diabetes', 'appetite', 'pedal edema']
    classes = ['notckd', 'ckd']

    # Print the tree to console in text form 
    tree_text = tree.export_text(dt, feature_names = features)
    print(tree_text)

    # Plot the tree and save it
    fig = plt.figure(figsize=(25,20))
    my_tree = tree.plot_tree(dt, feature_names = features, class_names = classes, filled = True)
    fig.savefig("decision_tree.png")

if __name__ == "__main__":
    data = pd.read_csv('kidneyChronic.csv')
    pre_processed_df = pre_process_data(data)
    decision_tree = train_classifier(pre_processed_df)
    plot_decision_tree(decision_tree)
